GPU_TEST_VERSION = 1.0.0
GPU_TEST_SITE = $(BR2_EXTERNAL_Bianbu_PATH)/../package-src/gpu-test
GPU_TEST_SITE_METHOD = local
GPU_TEST_LICENSE = GPLv2
GPU_TEST_INSTALL_TARGET = YES
GPU_TEST_CONF_OPTS = -DCMAKE_INSTALL_PREFIX="/usr"

$(eval $(cmake-package))
