AI_SUPPORT_VERSION:=1.0.8
AI_SUPPORT_SITE = $(BR2_EXTERNAL_Bianbu_PATH)/../package-src/ai-support
AI_SUPPORT_SITE_METHOD = local
AI_SUPPORT_DEPENDENCIES += onnx-runtime opencv4

# CMAKE_BUILD_TYPE is driven by BR2_ENABLE_RUNTIME_DEBUG
AI_SUPPORT_CONF_OPTS = -DTEST=OFF \
                       -DORT_HOME=$(STAGING_DIR)/usr

ifeq ($(BR2_PACKAGE_AI_SUPPORT_DEMO),y)
AI_SUPPORT_CONF_OPTS += -DDEMO=ON
endif # BR2_PACKAGE_AI_SUPPORT_DEMO

$(eval $(cmake-package))
